# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  render:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    
    - name: Folder Check
      run: apt-get install java-common default-jre-headless ffmpeg
      
    - name: Install Blender
      run: apt update
      
    - name: Folder Check
      run: apt remove libtcmalloc-minimal4
      
    - name: Install Blender
      run: apt install libtcmalloc-minimal4
      
    - name: Folder Check
      run: apt install libboost-all-dev
        
    - name: Folder Check
      run: apt install libgl1-mesa-dev
        
    - name: Create render directory
      run: apt install libglu1-mesa libsm-dev
      
    - name: Folder Check
      run: wget https://www.sheepit-renderfarm.com/media/applet/sheepit-client-6.21338.0.jar
    
    - name: Create render directory
      run: Content
      
    - name: Render
      run: java -jar sheepit-client-6.21338.0.jar -ui oneLine/text -cache-dir /content/cache -compute-method $computemethod -login ${{ github.event.inputs.username }} -password ${{ github.event.inputs.password }} -ui text
